apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: scale-rules
  namespace: openshift-monitoring
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/openshift-monitoring/prometheusrules/scale-rules
spec:
  groups:
  - name: scale.rules
    rules:
    - alert: etcdDatabaseWriteSurge
      annotations:
        message: 'Observed surge in etcd writes leading to increase 50% increase in database size over the past four hours, please check as it might be disruptive.'
      expr: |
        increase(((etcd_mvcc_db_total_size_in_bytes/etcd_server_quota_backend_bytes)*100)[240m:1m]) > 50
      labels:
        severity: warning
