apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: scale-rules
  namespace: openshift-monitoring
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/openshift-monitoring/prometheusrules/scale-rules
spec:
  groups:
  - name: scale.rules
    rules:
    - alert: etcdDatabaseSizeAlmostFull
      annotations:
        message: etcd database size is almost full, please defrag or increase the quota as the writes to etcd will be disabled when it is full.'
      expr: |
        (etcd_mvcc_db_total_size_in_bytes/etcd_server_quota_backend_bytes)*100 > 95
      labels:
        severity: critical
